-- return {
--   {
--     "zbirenbaum/copilot.lua",
--     config = function()
--       require("copilot").setup({
--         suggestion = { enabled = false },
--         panel = { enabled = false }
--       })
--     end
--   },
--   {
--     "CopilotC-Nvim/CopilotChat.nvim",
--     dependencies = {
--       { "zbirenbaum/copilot.lua" },
--       { "nvim-lua/plenary.nvim" },
--     },
--     build = "make tiktoken",
--     config = function()
--       require("CopilotChat").setup()
--     end
--   }
-- }
